#!/bin/bash

TMPDIR=
PREVDIR=`pwd`
export SCRIPT=$0
SCRIPTDIR=`dirname $0`

pushd $SCRIPTDIR >/dev/null
SCRIPTDIR=`pwd`
popd >/dev/null

set -u
set -e
trap onexit INT
trap onexit TERM
trap onexit EXIT

onexit()
{
	cd $PREVDIR
	if [ ! "$TMPDIR" = "" ]; then
		if [ ! "$PLATFORM" = "windows" ]; then
			RESULTS=`find $TMPDIR -uid 0 -print -quit`
			if [ ! -z "$RESULTS" -a ! `uid` -eq 0 ]; then
				sudo rm -rf $TMPDIR
			else
				rm -rf $TMPDIR
			fi
		else
			rm -rf $TMPDIR
		fi
	fi
}

PLATFORM=

case "`uname -s`" in
Linux)  export PLATFORM=linux ;;
Darwin) export PLATFORM=macos ;;
MINGW*) export PLATFORM=windows ;;
MSYS*)  export PLATFORM=windows ;;
*)      echo "Unsupported platform";  exit 1 ;;
esac

uid()
{
  id | cut -f2 -d = | cut -f1 -d \(;
}

usage()
{
	echo
	echo "USAGE: $SCRIPT [options] [branch/tag (default = main)]"
	echo
	echo "Options:"
	echo "-b <dir> = Specify build directory"
	echo "           (default = ~/src/tjj.nightly/$BUILD)"
	echo "-e = Use existing source tarball in the build directory"
	echo "-f = Force new build (deletes all existing build files in the build directory)"
	echo "-fb = Use existing source tarball in the build directory, but force new"
	echo "      binaries to be built for this platform"
	echo "-l = Generate file list and HTML index"
	echo "-r <url> = Specify Git repository URL"
	echo "           (default = $DEFAULT_REPO)"
	echo "-d <dir> = Build from existing source directory, located under <dir>"
	echo "           (useful for continuous integration)"
	echo "-s = Generate source package(s) only"
	echo "-v = Verbose (show the output of the build in real time)"
	echo
	exit 1
}

update_list()
{
	if [ ! -d $OUTDIR/files ]; then
		echo
		echo Build does not exist in $OUTDIR/files!
		echo
		exit 1
	fi
	cd $OUTDIR/files
	if [ -f files.txt ]; then rm -f files.txt; fi
	if [ -f ../files.txt ]; then rm -f ../files.txt; fi
	if [ -f index.html ]; then rm -f index.html; fi
	if [ -f ../index.html ]; then rm -f ../index.html; fi
	echo "<html><body><table border=1 cellpadding=5>" >../index.html
	echo "<tr><th>File</th><th>Size</th><th>Date</th><th>MD5 sum</th></tr>" >>../index.html
	for i in *; do
		if [ -d $i ]; then continue; fi
		LSL=`ls -l $i`
		SIZE=
		DATE=
		MD5=
		if [ ! -d $i ]; then
			SIZE=`echo $LSL | awk '{print $5}'`
			DATE=`echo $LSL | awk '{print $6" "$7}'`
			MD5=`md5sum -b $i | awk '{print $1}'`
		fi
		echo -e "$i\t$SIZE\t\t$DATE\t$MD5" >>../files.txt
		echo -e "<tr><td><a href=\"$i\">$i</a></td><td>$SIZE</td><td>$DATE</td><td>$MD5</td></tr>" >>../index.html
	done
	echo "</html></body>" >>../index.html
	mv ../files.txt .
	mv ../index.html .
}

BUILD=`date +%Y%m%d`
export OUTDIR=$HOME/src/tjj.nightly/$BUILD
LATEST=1

FORCE=0
export FORCEBINARY=0
SRCONLY=0
NOSRC=0
UPDATELIST=0
VERBOSE=0
TAG=main
DEFAULT_REPO=https://github.com/libjpeg-turbo/turbojpeg-java.git
REPO=$DEFAULT_REPO
SRCDIR=

while [ $# -gt 0 ]; do
	if [ "$1" = "-f" ]; then
		FORCE=1
	elif [ "$1" = "-fb" ]; then
		export FORCEBINARY=1
		NOSRC=1
	elif [ "$1" = "-s" ]; then
		SRCONLY=1
	elif [ "$1" = "-e" ]; then
		NOSRC=1
	elif [ "$1" = "-b" ]; then
		OUTDIR=$2
		LATEST=0
		shift
	elif [ "$1" = "-l" ]; then
		UPDATELIST=1
	elif [ "$1" = "-v" ]; then
		VERBOSE=1
	elif [ "$1" = "-r" ]; then
		REPO=$2
		shift
	elif [ "$1" = "-d" ]; then
		SRCDIR=$2
		shift
	elif [ "$1" = "-h" -o "$1" = "-?" ]; then
		usage
	else
		TAG=$1
	fi
	shift
done

if [ $SRCONLY = 1 -a $NOSRC = 1 ]; then
	echo ERROR: Cannot specify -s with -fb or -e
	exit 1
fi

if [ $UPDATELIST = 1 ]; then
	update_list
	exit 0
fi

if [ ! -d $OUTDIR ]; then
	mkdir -p $OUTDIR/files
else
	if [ $FORCE = 0 -a $NOSRC = 0 ]; then
		if [ $SRCONLY = 0 ]; then
			echo
			echo Build already exists in $OUTDIR/files!
			echo "Run $SCRIPT -f to force a full rebuild"
			echo " or $SCRIPT -e to use existing source"
			echo
			exit 1
		fi
	else
		if [ $NOSRC = 0 ]; then
			if [ -d $OUTDIR/files ]; then
				rm -f $OUTDIR/files/*
				rmdir $OUTDIR/files
			fi
			rm -f $OUTDIR/*
			rmdir $OUTDIR
			mkdir -p $OUTDIR/files
		fi
	fi
fi

umask 022
if [ "$PLATFORM" = "windows" ]; then
	# /tmp maps to a directory in c:\Documents and Settings, which causes
	# barfage in the MinGW resource compiler because of the pathname
	# spaces.
	export TMPDIR=`mktemp -d /c/temp/tjjbuild.XXXXXX`
else
	export TMPDIR=`mktemp -d /tmp/tjjbuild.XXXXXX`
fi
cd $TMPDIR
if [ $NOSRC = 0 ]; then
	if [ ! "$SRCDIR" = "" ]; then
		echo Using existing source directory $SRCDIR ...
		DIR=$SRCDIR
	else
		echo Checking out TurboJPEG/Java from $TAG ...
		git clone --depth=1 -b $TAG $REPO turbojpeg-java
		DIR=turbojpeg-java
	fi
	echo Creating source tarball ...
	cp -R $DIR turbojpeg-java.pristine
	pushd turbojpeg-java.pristine
	rm -rf .git .gitattributes .github .gitignore
	popd
	pushd $DIR
	VERSION=`grep "set(VERSION" CMakeLists.txt | sed -e s/[^0-9\.]//g`
	if [ "$VERSION" = "" ]; then
		echo Could not parse version from CMakeLists.txt!
		exit 1
	fi
	if [ "$PLATFORM" = "windows" ]; then
		CC=cl cmake -G"Ninja" -DCMAKE_PREFIX_PATH=c:/libjpeg-turbo64/lib/cmake .
		ninja dist
	else
		cmake -G"Unix Makefiles" -DCMAKE_PREFIX_PATH=/opt/libjpeg-turbo/lib64/cmake .
		make dist
	fi
	popd
	mv $DIR/turbojpeg-java-$VERSION.tar.gz $OUTDIR/files/
	tar xfz $OUTDIR/files/turbojpeg-java-$VERSION.tar.gz
	diff -r turbojpeg-java.pristine turbojpeg-java-$VERSION
	rm -rf turbojpeg-java.pristine
	if [ -f $SCRIPTDIR/gpgsign ]; then
		. $SCRIPTDIR/gpgsign
		if [ -f $OUTDIR/files/turbojpeg-java-$VERSION.tar.gz.sig ]; then
			rm -f $OUTDIR/files/turbojpeg-java-$VERSION.tar.gz.sig
		fi
		gpg --pinentry-mode loopback --batch --default-key "$GPG_KEY_ID" --passphrase "$GPG_KEY_PASS" --detach-sig $OUTDIR/files/turbojpeg-java-$VERSION.tar.gz \
			|| gpg --batch --default-key "$GPG_KEY_ID" --passphrase "$GPG_KEY_PASS" --detach-sig $OUTDIR/files/turbojpeg-java-$VERSION.tar.gz
		gpg --verify $OUTDIR/files/turbojpeg-java-$VERSION.tar.gz.sig
	fi
	rm -rf turbojpeg-java-$VERSION
	if [ "$SRCDIR" = "" ]; then
		rm -rf turbojpeg-java
	fi
else
	if [ "$PLATFORM" = "linux" ]; then
		if ! ls $OUTDIR/files/turbojpeg-java-[0-9]*.tar.gz >/dev/null 2>&1 ]; then
			echo Source files do not exist!
			exit 1
		fi
	else
		if [ ! -f $OUTDIR/files/turbojpeg-java-[0-9]*.tar.gz ]; then
			echo Source tarball does not exist!
			exit 1
		fi
	fi
fi

if [ $SRCONLY = 1 ]; then
	exit 0
fi

echo Untarring TurboJPEG/Java ...
tar xfz $OUTDIR/files/turbojpeg-java-[0-9]*.tar.gz
echo   done.
echo Building TurboJPEG/Java for $PLATFORM...
if [ $VERBOSE = 1 ]; then
	set -o pipefail
	$SCRIPTDIR/buildtjj.$PLATFORM | tee $OUTDIR/log-$PLATFORM.txt
else
	$SCRIPTDIR/buildtjj.$PLATFORM > $OUTDIR/log-$PLATFORM.txt
fi
echo   done.

update_list

if [ "$PLATFORM" != "windows" -a $LATEST = 1 ]; then
	# sym links aren't implemented properly in MinGW
	if [ -h $OUTDIR/../latest ]; then rm $OUTDIR/../latest; fi
	ln -fs $BUILD $OUTDIR/../latest
fi

exit 0
