#!/bin/sh

set -u
set -e

if [ $# -lt 2 ]; then
	echo USAGE: $0 \<SourceForge user name\> \<Release name\>
	exit 1
fi

BUILDDIR=$HOME/src/ljt.nightly/latest/files
FRSDIR=/home/frs/project/libjpeg-turbo

SSHSERVER=$1,libjpeg-turbo@shell.sourceforge.net

if [ ! -d $BUILDDIR ]; then
	echo No nightly build to release!
	exit 1
fi

echo Uploading build ...
ssh $SSHSERVER create
ssh $SSHSERVER << EOF
	mkdir "$FRSDIR/$2"
EOF
scp $BUILDDIR/* "$SSHSERVER:$FRSDIR/'$2'/" || true
ssh $SSHSERVER << EOF
	rm "$FRSDIR/$2/files.txt" "$FRSDIR/$2/index.html"
	~/bin/createrepo -x 'OldFiles/*' -s sha1 --update "$FRSDIR"
EOF
exit 0
