#!/bin/sh

set -u
set -e

NAME=
TAG=
PRARG=

if [ $# -lt 2 ]; then
	echo "USAGE: $0 <Release name> <Release tag> [-prerelease]"
	exit 1
fi

NAME=$1
shift
TAG=$1
shift
while [ $# -gt 0 ]; do
	case "$1" in
	-p*) PRARG=--prerelease ;;
	esac
	shift
done

BUILDDIR=$HOME/src/ljt.nightly/$TAG/files
if [ ! -d $BUILDDIR ]; then
	echo "Cannot find release under $BUILDDIR."
	exit 1
fi

echo Pushing release to GitHub ...

gh release create -R libjpeg-turbo/libjpeg-turbo $PRARG --title "$NAME" \
	--verify-tag --notes-file $BUILDDIR/README.md $TAG ||
gh release edit -R libjpeg-turbo/libjpeg-turbo $PRARG --title "$NAME" \
	--verify-tag --notes-file $BUILDDIR/README.md $TAG

find $BUILDDIR -type f -depth 1 \
	! -name '*.txt' -a ! -name '*.md' -a ! -name '*.html' | while read file; do
	gh release upload -R libjpeg-turbo/libjpeg-turbo $TAG "$file" || true
done

echo GREAT SUCCESS!
