#!/bin/sh

set -u
set -e

if [ $# -lt 1 ]; then
	echo USAGE: $0 \<SourceForge user name\>
	exit -1
fi

BUILDDIR=$HOME/src/ljt.nightly/latest/files
PROJWEB=/home/project-web/libjpeg-turbo/htdocs/
SSHSERVER=$1,libjpeg-turbo@shell.sourceforge.net

if [ ! -d $BUILDDIR ]; then
	echo No nightly build to upload!
	exit -1
fi

echo Uploading build ...
chmod 644 $BUILDDIR/*
ssh $SSHSERVER create
ssh $SSHSERVER mkdir $PROJWEB/ljt.nightly || true
ssh $SSHSERVER rm $PROJWEB/ljt.nightly/* || true
scp $BUILDDIR/* $SSHSERVER:$PROJWEB/ljt.nightly

exit 0
