#!/bin/sh

set -u
set -e

if [ $# -lt 1 ]; then
	echo USAGE: $0 \<SourceForge user name\> [tag]
	exit -1
fi

TAG=
if [ $# -gt 1 ]; then
	TAG=.$2
fi

BUILDDIR=$HOME/src/ljt.nightly/latest/files
PROJWEB=/home/project-web/libjpeg-turbo/htdocs/
SSHSERVER=$1,libjpeg-turbo@shell.sourceforge.net

if [ ! -d $BUILDDIR ]; then
	echo No nightly build to upload!
	exit -1
fi

echo Uploading build ...
find $BUILDDIR -type f | while read f; do
	chmod 644 $f
done
find $BUILDDIR -type d | while read d; do
	chmod 755 $d
done
ssh $SSHSERVER create
ssh $SSHSERVER mkdir $PROJWEB/ljt.nightly$TAG || true
ssh $SSHSERVER rm -r $PROJWEB/ljt.nightly$TAG/* || true
scp -r $BUILDDIR/* $SSHSERVER:$PROJWEB/ljt.nightly$TAG

exit 0
